/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gregoriandate2stardewdateconverter;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jason
 */
public class GUI extends javax.swing.JFrame
{

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jMonthComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDayComboBox = new javax.swing.JComboBox<>();
        jYearField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResultArea = new javax.swing.JTextArea();
        jConvertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SV Date Converter");
        setResizable(false);

        jLabel1.setText("Date To Convert");

        jMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jMonthComboBox.setToolTipText("Month");
        jMonthComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMonthComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Month");
        jLabel2.setToolTipText("");

        jDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jYearField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jYearFieldActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Day");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Year");

        jLabel5.setText("Result:");

        jResultArea.setEditable(false);
        jResultArea.setColumns(20);
        jResultArea.setRows(5);
        jScrollPane1.setViewportView(jResultArea);

        jConvertButton.setText("Convert");
        jConvertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jConvertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jConvertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMonthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDayComboBox, 0, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jYearField)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jConvertButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMonthComboBoxActionPerformed
    {//GEN-HEADEREND:event_jMonthComboBoxActionPerformed
        if( jMonthComboBox.getSelectedItem().toString().equals("February"))
        {
            jDayComboBox.setModel(mon29);
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("April") || jMonthComboBox.getSelectedItem().toString().equals("June") || jMonthComboBox.getSelectedItem().toString().equals("September") || jMonthComboBox.getSelectedItem().toString().equals("November"))
        {
            jDayComboBox.setModel(mon30);
        }
        else
        {
            jDayComboBox.setModel(mon31);
        }
    }//GEN-LAST:event_jMonthComboBoxActionPerformed

    private void jYearFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jYearFieldActionPerformed
    {//GEN-HEADEREND:event_jYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jYearFieldActionPerformed

    private void jConvertButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jConvertButtonActionPerformed
    {//GEN-HEADEREND:event_jConvertButtonActionPerformed
        int month;
        int day = Integer.parseInt(jDayComboBox.getSelectedItem().toString());
        int year = Integer.parseInt(jYearField.getText());
        
        if(jMonthComboBox.getSelectedItem().toString().equals("January"))
        {
            month = 1;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("February"))
        {
            month = 2;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("March"))
        {
            month = 3;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("April"))
        {
            month = 4;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("May"))
        {
            month = 5;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("June"))
        {
            month = 6;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("July"))
        {
            month = 7;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("August"))
        {
            month = 8;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("September"))
        {
            month = 9;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("October"))
        {
            month = 10;
        }
        else if(jMonthComboBox.getSelectedItem().toString().equals("November"))
        {
            month = 11;
        }
        else
        {
            month = 12;
        }
        
        jResultArea.setText(main.fullConversion(month, day, year));
    }//GEN-LAST:event_jConvertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    Methods main = new Methods();
    String[] arr29 = new String[]{"1", "2", "3" ,"4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"};
    String[] arr30 = new String[]{"1", "2", "3" ,"4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"};
    String[] arr31 = new String[]{"1", "2", "3" ,"4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
    DefaultComboBoxModel mon29 = new DefaultComboBoxModel( arr29 );
    DefaultComboBoxModel mon30 = new DefaultComboBoxModel( arr30 );
    DefaultComboBoxModel mon31 = new DefaultComboBoxModel( arr31 );
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConvertButton;
    private javax.swing.JComboBox<String> jDayComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jMonthComboBox;
    private javax.swing.JTextArea jResultArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jYearField;
    // End of variables declaration//GEN-END:variables
}
